# Generated by Django 3.0.7 on 2020-06-23 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mathis.Location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shield', models.CharField(max_length=200)),
                ('team_points', models.IntegerField(default=0)),
                ('team_class', models.IntegerField(default=0)),
                ('team_type', models.IntegerField(default=0)),
                ('team_active', models.IntegerField(default=1)),
                ('position_history', models.CharField(default=None, max_length=1000)),
                ('score_history', models.CharField(default=None, max_length=1000)),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mathis.Location')),
                ('stadium', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mathis.Stadium')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identif', models.IntegerField(blank=True, default=0)),
                ('goals', models.IntegerField(blank=True, default=None)),
                ('assistances', models.IntegerField(blank=True, default=None)),
                ('assistant', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assist', to='mathis.Player')),
                ('fair_play', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fair_play', to='mathis.Team')),
                ('goal_scorer', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scorer', to='mathis.Player')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathis.Team'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_team_a', models.IntegerField(default=0)),
                ('goals_team_b', models.IntegerField(default=0)),
                ('goals_team_ap', models.IntegerField(default=0)),
                ('goals_team_bp', models.IntegerField(default=0)),
                ('phase_id', models.IntegerField(default=0)),
                ('group_id', models.IntegerField(default=0)),
                ('dt', models.IntegerField(default=0)),
                ('team_a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='mathis.Team')),
                ('team_b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='mathis.Team')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathis.Tournament')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
