# Generated by Django 3.0.7 on 2020-06-05 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shield', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.IntegerField(default=0)),
                ('assistances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist', to='mathis.Player')),
                ('goal_scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorer', to='mathis.Player')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='mathis.Team')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='mathis.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_points', models.IntegerField(default=0)),
                ('team_class', models.IntegerField(default=0)),
                ('team_type', models.IntegerField(default=0)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathis.Team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathis.Team'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_team_a', models.IntegerField(default=0)),
                ('goals_team_b', models.IntegerField(default=0)),
                ('phase_id', models.IntegerField(default=0)),
                ('group_id', models.IntegerField(default=0)),
                ('team_a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='mathis.Team')),
                ('team_b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='mathis.Team')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathis.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('stadium', models.CharField(max_length=200)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathis.Team')),
            ],
        ),
    ]
