# Generated by Django 3.0.7 on 2020-06-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['score']},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_points',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(choices=[('AUSTRIA', 'Austria'), ('BELARUS', 'Belarus'), ('BELGIUM', 'Belgium'), ('BOSNIA_AND_HERZEGOVINA', 'Bosnia and Gerzegovina'), ('BULGARIA', 'Bulgaria'), ('CROATIA', 'Croatia'), ('CYPRUS', 'Cyprus'), ('DENMARK', 'Denmark'), ('ENGLAND', 'England'), ('FINLAND', 'Finland'), ('FRANCE', 'France'), ('GERMANY', 'Germany'), ('GREECE', 'Greece'), ('ITALY', 'Italy'), ('NETHERLANDS', 'Netherlands'), ('NORWAY', 'Norway'), ('PORTUGAL', 'Portugal'), ('SERBIA', 'Switzerland'), ('SCOTLAND', 'Scotland'), ('SLOVAKIA', 'Slovakia'), ('SLOVENIA', 'Slovenia'), ('SWEDEN', 'Sweden'), ('SWITZERLAND', 'Switzerland'), ('TURKEY', 'Turkey')], default='AUSTRIA', max_length=50),
        ),
    ]
