# Generated by Django 3.0.7 on 2020-06-19 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='goals_team_a',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='assistances',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='goal_scorer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scorer', to='mathis.Player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='goals',
            field=models.IntegerField(default=None),
        ),
    ]
