# Generated by Django 3.0.7 on 2020-06-06 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Statistic',
        ),
    ]
