# Generated by Django 3.0.7 on 2020-06-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathis', '0002_auto_20200622_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(choices=[('AUSTRIA', 'Austria'), ('BELARUS', 'Belarus'), ('BELGIUM', 'Belgium'), ('BOSNIA_AND_HERZEGOVINA', 'Bosnia and Gerzegovina'), ('BULGARIA', 'Bulgaria'), ('CROATIA', 'Croatia'), ('CYPRUS', 'Cyprus'), ('DENMARK', 'Denmark'), ('ENGLAND', 'England'), ('FINLAND', 'Finland'), ('FRANCE', 'France'), ('GERMANY', 'Germany'), ('GREECE', 'Greece'), ('ITALY', 'Italy'), ('NETHERLANDS', 'Netherlands'), ('NORWAY', 'Norway'), ('PORTUGAL', 'Portugal'), ('SERBIA', 'Switzerland'), ('SCOTLAND', 'Scotland'), ('SLOVAKIA', 'Slovakia'), ('SLOVENIA', 'Slovenia'), ('SPAIN', 'Spain'), ('SWEDEN', 'Sweden'), ('SWITZERLAND', 'Switzerland'), ('TURKEY', 'Turkey')], default='AUSTRIA', max_length=50),
        ),
    ]
