# Generated by Django 3.0.7 on 2020-06-19 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathis', '0002_auto_20200618_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='assistances',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='assistant',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assist', to='mathis.Player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='fair_play',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fair_play', to='mathis.Team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='goal_scorer',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scorer', to='mathis.Player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='goals',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
