# Generated by Django 3.0.7 on 2020-06-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathis', '0003_auto_20200618_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='second',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='winner',
        ),
    ]
