# Generated by Django 3.0.7 on 2020-06-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathis', '0004_auto_20200618_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='identif',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
