# Generated by Django 3.0.7 on 2020-06-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathis', '0005_tournament_identif'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='goals_team_ap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='goals_team_bp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='goals_team_a',
            field=models.IntegerField(default=0),
        ),
    ]
