# Generated by Django 3.0.7 on 2020-06-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathis', '0006_auto_20200621_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_active',
            field=models.IntegerField(default=0),
        ),
    ]
