# Generated by Django 3.0.7 on 2020-06-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathis', '0007_team_team_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_active',
            field=models.IntegerField(default=1),
        ),
    ]
